server:
  port: 3340
  hostname: http://localhost:3340

db:
  host: localhost
  username: url_shortner
  password: url_shortner
  db_name: url_shortner_db
  port: 3306

security:
  jwt:
    secret_key: secret_key
    issuer: issue